name: 'WikiPeopleStats'
on:
  push:
    branches: [ main ]

env:
  cli-version: '2.6.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload translations
        uses: simplelocalize/github-action-cli@v3
        with:
          api-key: ${{ secrets.SIMPLELOCALIZE_API_KEY }}
          command: 'upload'
          cli-version: ${{ env.cli-version }}
          args: '--uploadPath ./languages/{lang}.json --uploadFormat single-language-json'
